// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServiceClient interface {
	// リクエストを渡して、レスポンスを返す
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// レスポンスにstreamを付けることでSVは複数レスポンスを返せる
	HelloAmp(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (HelloService_HelloAmpClient, error)
	// リクエストにstreamを付けることでクライアントは複数リクエストを渡せる
	HelloManyTimes(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloManyTimesClient, error)
	// リクエスト、レスポンスにstreamを付けることで双方向でストリーミングできる
	HelloEveryone(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloEveryoneClient, error)
}

type helloServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServiceClient(cc grpc.ClientConnInterface) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) HelloAmp(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (HelloService_HelloAmpClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[0], "/hello.HelloService/HelloAmp", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceHelloAmpClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HelloService_HelloAmpClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type helloServiceHelloAmpClient struct {
	grpc.ClientStream
}

func (x *helloServiceHelloAmpClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) HelloManyTimes(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloManyTimesClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[1], "/hello.HelloService/HelloManyTimes", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceHelloManyTimesClient{stream}
	return x, nil
}

type HelloService_HelloManyTimesClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloResponse, error)
	grpc.ClientStream
}

type helloServiceHelloManyTimesClient struct {
	grpc.ClientStream
}

func (x *helloServiceHelloManyTimesClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceHelloManyTimesClient) CloseAndRecv() (*HelloResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *helloServiceClient) HelloEveryone(ctx context.Context, opts ...grpc.CallOption) (HelloService_HelloEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &HelloService_ServiceDesc.Streams[2], "/hello.HelloService/HelloEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloServiceHelloEveryoneClient{stream}
	return x, nil
}

type HelloService_HelloEveryoneClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type helloServiceHelloEveryoneClient struct {
	grpc.ClientStream
}

func (x *helloServiceHelloEveryoneClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *helloServiceHelloEveryoneClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloServiceServer is the server API for HelloService service.
// All implementations must embed UnimplementedHelloServiceServer
// for forward compatibility
type HelloServiceServer interface {
	// リクエストを渡して、レスポンスを返す
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// レスポンスにstreamを付けることでSVは複数レスポンスを返せる
	HelloAmp(*HelloRequest, HelloService_HelloAmpServer) error
	// リクエストにstreamを付けることでクライアントは複数リクエストを渡せる
	HelloManyTimes(HelloService_HelloManyTimesServer) error
	// リクエスト、レスポンスにstreamを付けることで双方向でストリーミングできる
	HelloEveryone(HelloService_HelloEveryoneServer) error
	mustEmbedUnimplementedHelloServiceServer()
}

// UnimplementedHelloServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (UnimplementedHelloServiceServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHelloServiceServer) HelloAmp(*HelloRequest, HelloService_HelloAmpServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloAmp not implemented")
}
func (UnimplementedHelloServiceServer) HelloManyTimes(HelloService_HelloManyTimesServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloManyTimes not implemented")
}
func (UnimplementedHelloServiceServer) HelloEveryone(HelloService_HelloEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloEveryone not implemented")
}
func (UnimplementedHelloServiceServer) mustEmbedUnimplementedHelloServiceServer() {}

// UnsafeHelloServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServiceServer will
// result in compilation errors.
type UnsafeHelloServiceServer interface {
	mustEmbedUnimplementedHelloServiceServer()
}

func RegisterHelloServiceServer(s grpc.ServiceRegistrar, srv HelloServiceServer) {
	s.RegisterService(&HelloService_ServiceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_HelloAmp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServiceServer).HelloAmp(m, &helloServiceHelloAmpServer{stream})
}

type HelloService_HelloAmpServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type helloServiceHelloAmpServer struct {
	grpc.ServerStream
}

func (x *helloServiceHelloAmpServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HelloService_HelloManyTimes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).HelloManyTimes(&helloServiceHelloManyTimesServer{stream})
}

type HelloService_HelloManyTimesServer interface {
	SendAndClose(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloServiceHelloManyTimesServer struct {
	grpc.ServerStream
}

func (x *helloServiceHelloManyTimesServer) SendAndClose(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceHelloManyTimesServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HelloService_HelloEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HelloServiceServer).HelloEveryone(&helloServiceHelloEveryoneServer{stream})
}

type HelloService_HelloEveryoneServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type helloServiceHelloEveryoneServer struct {
	grpc.ServerStream
}

func (x *helloServiceHelloEveryoneServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *helloServiceHelloEveryoneServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HelloService_ServiceDesc is the grpc.ServiceDesc for HelloService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloAmp",
			Handler:       _HelloService_HelloAmp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HelloManyTimes",
			Handler:       _HelloService_HelloManyTimes_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HelloEveryone",
			Handler:       _HelloService_HelloEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
